name: weather_app_new
description: A simple weather app using Flutter and OpenWeather API

publish_to: 'none'

version: 1.0.0+1
# version: 1.0.0+1: Phiên bản của ứng dụng.
# Định dạng là <major>.<minor>.<patch>+<build>. Ở đây:
# 1.0.0 là phiên bản chính (major: 1, minor: 0, patch: 0).
# +1 là số build, thường tăng lên khi bạn tạo các bản build mới mà không thay đổi phiên bản chính.

#todo: moi truong sdk

environment:
  sdk: '>=3.0.0 <4.0.0'

#todo: cac phu thuoc

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true